packages:
  - apps/*
  - packages/*

allowBuilds:
  argon2: true
  esbuild: true
  sharp: true
  supabase: true
  unrs-resolver: true

engineStrict: true
lockfile: true
nodeVersion: 24.18.0
preferFrozenLockfile: true
saveExact: true
sharedWorkspaceLockfile: true
strictPeerDependencies: false
